# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Le livre de Jonas
author: Jonas Verbois
logo: src/images/logo.png

exclude_patterns: [_build, venv, README.md]
# Information about where the book exists on the web
repository:
  url: https://github.com/executablebooks/jupyter-book  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
