# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Le livre de Jonas
author: Jonas Verbois
logo: src/images/logo.png

exclude_patterns: [_build, venv, README.md]
# Information about where the book exists on the web

execute: 
  execute_notebooks: force
repository:
  url: https://github.com/jverbois/book-jonas
  path_to_book: docs

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
